### ISSUE TITLE
ARM64 Docker image feature

### ISSUE THREAD

**Issue by nlamirault** [fjogeleit/policy-reporter-kyverno-plugin#1]
It would be really good to have an arm64 compatible Docker image to deploy the application on a Kubernetes Raspberry PI cluster

**Comment by fjogeleit** [comment]
Available with Version 0.3.0: https://hub.docker.com/layers/fjogeleit/policy-reporter-kyverno-plugin/0.3.0/images/sha256-2ea8be324d1d17ec45b03f0794e30d73d3ef751a29b0ca25d1e215dfc98240c5?context=repo
